from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QDialog


class Ui_Create_event(QDialog):
    def __init__(self):
        super(Ui_Create_event, self).__init__()
        self.setObjectName("Create_event")
        self.resize(542, 319)
        self.label_create_event = QtWidgets.QLabel(self)
        self.label_create_event.setGeometry(QtCore.QRect(120, 20, 351, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_create_event.setFont(font)
        self.label_create_event.setObjectName("label_create_event")
        self.event_name = QtWidgets.QLineEdit(self)
        self.event_name.setGeometry(QtCore.QRect(10, 60, 521, 25))
        self.event_name.setObjectName("event_name")
        self.event_data = QtWidgets.QDateEdit(self)
        self.event_data.setGeometry(QtCore.QRect(10, 140, 110, 26))
        self.event_data.setDateTime(QtCore.QDateTime(QtCore.QDate(2023, 1, 1), QtCore.QTime(0, 0, 0)))
        self.event_data.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(2050, 12, 30), QtCore.QTime(23, 59, 59)))
        self.event_data.setMinimumDate(QtCore.QDate(1752, 9, 15))
        self.event_data.setObjectName("event_data")
        self.event_country = QtWidgets.QLineEdit(self)
        self.event_country.setGeometry(QtCore.QRect(290, 140, 241, 25))
        self.event_country.setObjectName("event_country")
        self.event_time = QtWidgets.QTimeEdit(self)
        self.event_time.setGeometry(QtCore.QRect(130, 140, 118, 26))
        self.event_time.setTime(QtCore.QTime(10, 0, 0))
        self.event_time.setObjectName("event_time")
        self.event_city = QtWidgets.QLineEdit(self)
        self.event_city.setGeometry(QtCore.QRect(290, 180, 241, 25))
        self.event_city.setObjectName("event_city")
        self.event_theme = QtWidgets.QLineEdit(self)
        self.event_theme.setGeometry(QtCore.QRect(10, 100, 521, 25))
        self.event_theme.setObjectName("event_theme")
        self.pushButton_save_event = QtWidgets.QPushButton(self)
        self.pushButton_save_event.setGeometry(QtCore.QRect(430, 280, 101, 25))
        self.pushButton_save_event.setObjectName("pushButton_save_event")
        self.event_type = QtWidgets.QComboBox(self)
        self.event_type.setGeometry(QtCore.QRect(10, 180, 241, 25))
        self.event_type.setObjectName("event_type")
        self.event_type.addItem("")
        self.event_type.addItem("")
        self.event_comment = QtWidgets.QLineEdit(self)
        self.event_comment.setGeometry(QtCore.QRect(10, 220, 521, 25))
        self.event_comment.setObjectName("event_comment")
        self.pushButton_cancel = QtWidgets.QPushButton(self)
        self.pushButton_cancel.setGeometry(QtCore.QRect(320, 280, 101, 25))
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.label_username_role = QtWidgets.QLabel(self)
        self.label_username_role.setGeometry(QtCore.QRect(240, 0, 301, 20))
        self.label_username_role.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_username_role.setObjectName("label_username_role")

        self.retranslateUi(self)
        # Нажатия на кнопки
        self.pushButton_save_event.clicked.connect(self.show)
        self.pushButton_cancel.clicked.connect(self.close)
        QtCore.QMetaObject.connectSlotsByName(self)

        self.setTabOrder(self.event_name, self.event_theme)
        self.setTabOrder(self.event_theme, self.event_data)
        self.setTabOrder(self.event_data, self.event_time)
        self.setTabOrder(self.event_time, self.event_country)
        self.setTabOrder(self.event_country, self.event_type)
        self.setTabOrder(self.event_type, self.event_city)
        self.setTabOrder(self.event_city, self.event_comment)
        self.setTabOrder(self.event_comment, self.pushButton_cancel)
        self.setTabOrder(self.pushButton_cancel, self.pushButton_save_event)

    def retranslateUi(self, Create_event):
        _translate = QtCore.QCoreApplication.translate
        Create_event.setWindowTitle(_translate("Create_event", "Логистик (update 23.02)"))
        self.label_create_event.setText(_translate("Create_event", "Создание нового мероприятия"))
        self.event_name.setPlaceholderText(_translate("Create_event", "Наименование мероприятия..."))
        self.event_country.setPlaceholderText(_translate("Create_event", "Страна..."))
        self.event_city.setPlaceholderText(_translate("Create_event", "Город..."))
        self.event_theme.setPlaceholderText(_translate("Create_event", "Тема мероприятия..."))
        self.pushButton_save_event.setText(_translate("Create_event", "Сохранить"))
        self.event_type.setItemText(0, _translate("Create_event", "НИР"))
        self.event_type.setItemText(1, _translate("Create_event", "Кадавр"))
        self.event_comment.setPlaceholderText(_translate("Create_event", "Комментарий..."))
        self.pushButton_cancel.setText(_translate("Create_event", "Отмена"))
        self.label_username_role.setText(_translate("Create_event", "Фомина Ирина (Администратор)"))
        self.move_to_center()

    def move_to_center(self):
        desktop = QApplication.desktop()
        desktop.screenGeometry()
        x = (desktop.width() - self.width()) // 2
        y = (desktop.height() - self.height()) // 2
        self.move(x, y)
