from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QDialog


class Ui_Create_inspector(QDialog):
    def __init__(self):
        super(Ui_Create_inspector, self).__init__()
        self.setObjectName("Create_inspector")
        self.resize(431, 368)
        self.label_username_role = QtWidgets.QLabel(self)
        self.label_username_role.setGeometry(QtCore.QRect(130, 0, 301, 20))
        self.label_username_role.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_username_role.setObjectName("label_username_role")
        self.lineEdit_second_name = QtWidgets.QLineEdit(self)
        self.lineEdit_second_name.setGeometry(QtCore.QRect(10, 100, 131, 25))
        self.lineEdit_second_name.setObjectName("lineEdit_second_name")
        self.lineEdit_email = QtWidgets.QLineEdit(self)
        self.lineEdit_email.setGeometry(QtCore.QRect(10, 140, 131, 25))
        self.lineEdit_email.setObjectName("lineEdit_email")
        self.lineEdit_last_name = QtWidgets.QLineEdit(self)
        self.lineEdit_last_name.setGeometry(QtCore.QRect(290, 100, 131, 25))
        self.lineEdit_last_name.setObjectName("lineEdit_last_name")
        self.lineEdit_password = QtWidgets.QLineEdit(self)
        self.lineEdit_password.setGeometry(QtCore.QRect(10, 180, 131, 25))
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.pushButton_generate = QtWidgets.QPushButton(self)
        self.pushButton_generate.setGeometry(QtCore.QRect(150, 180, 131, 25))
        self.pushButton_generate.setObjectName("pushButton_generate")
        self.checkBox_disabled_inspector = QtWidgets.QCheckBox(self)
        self.checkBox_disabled_inspector.setGeometry(QtCore.QRect(10, 300, 221, 23))
        self.checkBox_disabled_inspector.setObjectName("checkBox_disabled_inspector")
        self.label_create_inspector = QtWidgets.QLabel(self)
        self.label_create_inspector.setGeometry(QtCore.QRect(120, 20, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_create_inspector.setFont(font)
        self.label_create_inspector.setObjectName("label_create_inspector")
        self.lineEdit_phone_number = QtWidgets.QLineEdit(self)
        self.lineEdit_phone_number.setGeometry(QtCore.QRect(150, 60, 131, 25))
        self.lineEdit_phone_number.setObjectName("lineEdit_phone_number")
        self.lineEdit_first_name = QtWidgets.QLineEdit(self)
        self.lineEdit_first_name.setGeometry(QtCore.QRect(150, 100, 131, 25))
        self.lineEdit_first_name.setObjectName("lineEdit_first_name")
        self.comboBox_select_organization = QtWidgets.QComboBox(self)
        self.comboBox_select_organization.setGeometry(QtCore.QRect(290, 140, 131, 25))
        self.comboBox_select_organization.setObjectName("comboBox_select_organization")
        self.comboBox_select_organization.addItem("")
        self.comboBox_select_organization.addItem("")
        self.comboBox_select_organization.addItem("")
        self.pushButton_save = QtWidgets.QPushButton(self)
        self.pushButton_save.setGeometry(QtCore.QRect(330, 330, 89, 25))
        self.pushButton_save.setObjectName("pushButton_save")
        self.pushButton_cancel = QtWidgets.QPushButton(self)
        self.pushButton_cancel.setGeometry(QtCore.QRect(230, 330, 89, 25))
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.lineEdit_city = QtWidgets.QLineEdit(self)
        self.lineEdit_city.setGeometry(QtCore.QRect(150, 140, 131, 25))
        self.lineEdit_city.setObjectName("lineEdit_city")
        self.lineEdit_comment = QtWidgets.QLineEdit(self)
        self.lineEdit_comment.setGeometry(QtCore.QRect(10, 220, 411, 25))
        self.lineEdit_comment.setObjectName("lineEdit_comment")
        self.retranslateUi(self)

        # Нажатия на кнопки
        self.pushButton_generate.clicked.connect(self.lineEdit_password.selectAll)
        self.pushButton_save.clicked.connect(self.show)
        self.pushButton_cancel.clicked.connect(self.close)
        self.checkBox_disabled_inspector.stateChanged['int'].connect(self.show)
        QtCore.QMetaObject.connectSlotsByName(self)

        # Порядок выбора по Tab
        self.setTabOrder(self.lineEdit_second_name, self.lineEdit_first_name)
        self.setTabOrder(self.lineEdit_first_name, self.lineEdit_last_name)
        self.setTabOrder(self.lineEdit_last_name, self.lineEdit_email)
        self.setTabOrder(self.lineEdit_email, self.lineEdit_city)
        self.setTabOrder(self.lineEdit_city, self.comboBox_select_organization)
        self.setTabOrder(self.comboBox_select_organization, self.lineEdit_password)
        self.setTabOrder(self.lineEdit_password, self.pushButton_generate)
        self.setTabOrder(self.pushButton_generate, self.lineEdit_comment)
        self.setTabOrder(self.lineEdit_comment, self.checkBox_disabled_inspector)
        self.setTabOrder(self.checkBox_disabled_inspector, self.pushButton_cancel)
        self.setTabOrder(self.pushButton_cancel, self.pushButton_save)
        self.setTabOrder(self.pushButton_save, self.lineEdit_phone_number)

    def retranslateUi(self, Create_inspector):
        _translate = QtCore.QCoreApplication.translate
        Create_inspector.setWindowTitle(_translate("Create_inspector", "Логистик  (update 23.02)"))
        self.label_username_role.setText(_translate("Create_inspector", "Фомина Ирина (Администратор)"))
        self.lineEdit_second_name.setPlaceholderText(_translate("Create_inspector", "Фамилия..."))
        self.lineEdit_email.setPlaceholderText(_translate("Create_inspector", "e-mail..."))
        self.lineEdit_last_name.setPlaceholderText(_translate("Create_inspector", "Отчество..."))
        self.lineEdit_password.setPlaceholderText(_translate("Create_inspector", "Пароль..."))
        self.pushButton_generate.setText(_translate("Create_inspector", "Сгенерировать"))
        self.checkBox_disabled_inspector.setText(_translate("Create_inspector", "Отключить учетную запись"))
        self.label_create_inspector.setText(_translate("Create_inspector", "Создание инспектора"))
        self.lineEdit_phone_number.setPlaceholderText(_translate("Create_inspector", "79265001020"))
        self.lineEdit_first_name.setPlaceholderText(_translate("Create_inspector", "Имя..."))
        self.comboBox_select_organization.setItemText(0, _translate("Create_inspector", "Организация"))
        self.comboBox_select_organization.setItemText(1, _translate("Create_inspector", "Мерц"))
        self.comboBox_select_organization.setItemText(2, _translate("Create_inspector", "Аллерган"))
        self.pushButton_save.setText(_translate("Create_inspector", "Сохранить"))
        self.pushButton_cancel.setText(_translate("Create_inspector", "Отмена"))
        self.lineEdit_city.setPlaceholderText(_translate("Create_inspector", "Город..."))
        self.lineEdit_comment.setPlaceholderText(_translate("Create_inspector", "Комментарий..."))
        self.move_to_center()

    def move_to_center(self):
        desktop = QApplication.desktop()
        desktop.screenGeometry()
        x = (desktop.width() - self.width()) // 2
        y = (desktop.height() - self.height()) // 2
        self.move(x, y)