# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_list_of_all_participants.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QDialog


class Ui_list_of_all_participants(QDialog):
    def __init__(self):
        super(Ui_list_of_all_participants, self).__init__()
        self.setObjectName("List_of_all_participants")
        self.resize(1016, 556)
        self.gridLayout_3 = QtWidgets.QGridLayout(self)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineEdit_find_participant = QtWidgets.QLineEdit(self)
        self.lineEdit_find_participant.setObjectName("lineEdit_find_participant")
        self.gridLayout_2.addWidget(self.lineEdit_find_participant, 0, 0, 1, 2)
        self.pushButton_find_event_2 = QtWidgets.QPushButton(self)
        self.pushButton_find_event_2.setObjectName("pushButton_find_event_2")
        self.gridLayout_2.addWidget(self.pushButton_find_event_2, 0, 2, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 6, 0, 1, 7)
        self.tree_participants_list = QtWidgets.QTreeWidget(self)
        self.tree_participants_list.setObjectName("tree_participants_list")
        self.tree_participants_list.headerItem().setText(0, "1")
        self.gridLayout_3.addWidget(self.tree_participants_list, 4, 0, 1, 7)
        self.pushButton_export_xls = QtWidgets.QPushButton(self)
        self.pushButton_export_xls.setObjectName("pushButton_export_xls")
        self.gridLayout_3.addWidget(self.pushButton_export_xls, 2, 5, 1, 1)
        self.pushButton_redact_participant = QtWidgets.QPushButton(self)
        self.pushButton_redact_participant.setObjectName("pushButton_redact_participant")
        self.gridLayout_3.addWidget(self.pushButton_redact_participant, 3, 1, 1, 1)
        self.pushButton_exit = QtWidgets.QPushButton(self)
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.gridLayout_3.addWidget(self.pushButton_exit, 2, 6, 1, 1)
        self.label_username_role = QtWidgets.QLabel(self)
        self.label_username_role.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_username_role.setObjectName("label_username_role")
        self.gridLayout_3.addWidget(self.label_username_role, 0, 5, 1, 2)
        self.pushButton_create_participant = QtWidgets.QPushButton(self)
        self.pushButton_create_participant.setObjectName("pushButton_create_participant")
        self.gridLayout_3.addWidget(self.pushButton_create_participant, 3, 0, 1, 1)
        self.label_find_event = QtWidgets.QLabel(self)
        self.label_find_event.setObjectName("label_find_event")
        self.gridLayout_3.addWidget(self.label_find_event, 5, 0, 1, 3)
        self.label_participants_list = QtWidgets.QLabel(self)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_participants_list.setFont(font)
        self.label_participants_list.setObjectName("label_participants_list")
        self.gridLayout_3.addWidget(self.label_participants_list, 2, 2, 1, 1)
        self.pushButton_delete_participant = QtWidgets.QPushButton(self)
        self.pushButton_delete_participant.setObjectName("pushButton_delete_participant")
        self.gridLayout_3.addWidget(self.pushButton_delete_participant, 3, 6, 1, 1)

        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self, List_of_all_participants):
        _translate = QtCore.QCoreApplication.translate
        List_of_all_participants.setWindowTitle(_translate("List_of_all_participants", "Общий список участников"))
        self.lineEdit_find_participant.setPlaceholderText(_translate("List_of_all_participants", "Поиск участника"))
        self.pushButton_find_event_2.setText(_translate("List_of_all_participants", "Найти"))
        self.pushButton_export_xls.setText(_translate("List_of_all_participants", "Export xls"))
        self.pushButton_redact_participant.setText(_translate("List_of_all_participants", "Редактировать участника"))
        self.pushButton_exit.setText(_translate("List_of_all_participants", "Выход"))

        #Сюда транслировать из Access или Ui_event_schedule
        self.label_username_role.setText(_translate("List_of_all_participants", "Фомина Ирина (Администратор)"))

        self.pushButton_create_participant.setText(_translate("List_of_all_participants", "Создать участника"))
        self.label_find_event.setText(_translate("List_of_all_participants", "Фильтры поиска участника:"))
        self.label_participants_list.setText(_translate("List_of_all_participants", "Общий список участников"))
        self.pushButton_delete_participant.setText(_translate("List_of_all_participants", "Удалить участника"))
